apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-cluster-admin-bindings
  annotations:
    policies.kyverno.io/title: Disallow Cluster Admin Role Bindings
    policies.kyverno.io/category: Security
    policies.kyverno.io/subject: RoleBinding, ClusterRoleBinding
    policies.kyverno.io/description: >-
      The cluster-admin ClusterRole provides super-user access to the cluster.
      Granting this role should be carefully controlled. This policy prevents
      workloads from being granted the cluster-admin ClusterRole through
      RoleBindings and ClusterRoleBindings.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: disallow-cluster-admin-rolebinding
    match:
      any:
      - resources:
          kinds:
          - RoleBinding
    validate:
      message: "RoleBinding cannot reference cluster-admin ClusterRole"
      deny:
        conditions:
          any:
          - key: "{{ request.object.roleRef.name }}"
            operator: Equals
            value: cluster-admin
          - key: "{{ request.object.roleRef.name }}"
            operator: Equals
            value: "cluster-admin"
  - name: disallow-cluster-admin-clusterrolebinding
    match:
      any:
      - resources:
          kinds:
          - ClusterRoleBinding
    validate:
      message: "ClusterRoleBinding cannot reference cluster-admin ClusterRole"
      deny:
        conditions:
          any:
          - key: "{{ request.object.roleRef.name }}"
            operator: Equals
            value: cluster-admin
          - key: "{{ request.object.roleRef.name }}"
            operator: Equals
            value: "cluster-admin"
  - name: disallow-cluster-admin-subjects
    match:
      any:
      - resources:
          kinds:
          - RoleBinding
          - ClusterRoleBinding
    validate:
      message: "Cannot bind cluster-admin role to any subjects"
      deny:
        conditions:
          all:
          - key: "{{ request.object.roleRef.kind }}"
            operator: Equals
            value: ClusterRole
          - key: "{{ request.object.roleRef.name }}"
            operator: Equals
            value: cluster-admin