name: Deploy Infra

on:
  push:
    branches:
      - "**"
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-infra.yml'

jobs:
  terraform:
    name: Apply Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Write SSH Pub Key
        run: |
          mkdir -p ./creds
          echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ./creds/id_rsa.pub

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY_INFRA }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY_INFRA }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY_INFRA }}
